apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-configure-vault
spec:
  template:
    spec:
      containers:
        - name: cassandra-configure-pki
          image: nathanmyles/vault-client:1.0.0
          command: ["/bin/sh"]
          args:
            - -ec
            - |
              curl http://local-vault.default/ca_cert.crt > /ca_cert.crt
              export VAULT_CACERT="/ca_cert.crt"
              export VAULT_ADDR="https://local-vault.default:8200"
              vault login root_token
              cat >> policy.hcl <<EOF
                path "pki/issue/cassandra-default" {
                  capabilities = ["create", "update"]
                }
              EOF
              vault policy write local-cassandra policy.hcl
              vault write auth/kubernetes/role/local-cassandra \
                bound_service_account_names=local-cassandra \
                bound_service_account_namespaces=default \
                policies=default,local-cassandra \
                ttl=1h
              vault write pki/roles/cassandra-default \
                  allowed_domains=local-cassandra.default \
                  allow_subdomains=true \
                  max_ttl=72h
      restartPolicy: Never
