apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-zookeeper
  labels:
    app: local-zookeeper
spec:
  serviceName: local-zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: local-zookeeper
  template:
    metadata:
      labels:
        app: local-zookeeper
    spec:
      containers:
      - name: local-zookeeper
        image: confluentinc/cp-zookeeper:5.3.1
        command: [ "bash", "-c"]
        args:
        - |
          echo $((${HOSTNAME//[!0-9]/}+1)) > /var/lib/zookeeper/data/myid
          /etc/confluent/docker/run
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_SERVER_PORT
            value: "2888"
          - name: ZOOKEEPER_ELECTION_PORT
            value: "3888"
          - name: ZOOKEEPER_SERVER_1
            value: "local-zookeeper-0.local-zookeeper.default:2888:3888"
#          - name: ZOOKEEPER_SERVER_2
#            value: "local-zookeeper-1.local-zookeeper.default:2888:3888"
#          - name: ZOOKEEPER_SERVER_3
#            value: "local-zookeeper-2.local-zookeeper.default:2888:3888"
          - name: ZOOKEEPER_DATA_DIR
            value: "/var/lib/zookeeper/data"
          - name: ZOOKEEPER_DATA_LOG_DIR
            value: "/var/lib/zookeeper/log"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
          - name: ZOOKEEPER_SYNC_LIMIT
            value: "2"
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - 'if [[ $(echo ruok | nc 127.0.0.1 2181) == "imok" ]]; then exit 0; else exit 1; fi'
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
