apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-schema-registry
  labels:
    app: local-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-schema-registry
  template:
    metadata:
      labels:
        app: local-schema-registry
    spec:
      serviceAccountName: local-schema-registry
      containers:
        - name: local-schema-registry
          image: confluentinc/cp-schema-registry:5.3.1
          command: [ "bash", "-c"]
          args:
            - |
              cp /schema_registry_config/schema-registry.properties /etc/schema-registry/schema-registry.properties
              schema-registry-start /etc/schema-registry/schema-registry.properties
          ports:
            - containerPort: 8081
              name: client
            - containerPort: 8082
              name: tls-client
          env:
            - name: SCHEMA_REGISTRY_DEBUG
              value: "true"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: config-volume
              mountPath: /schema_registry_config/
      volumes:
        - name: config-volume
          configMap:
            name: schema-registry-config
