apiVersion: v1
kind: Service
metadata:
  labels:
    app: local-schema-registry
  name: local-schema-registry
spec:
  type: LoadBalancer
  ports:
  - port: 8081
  selector:
    app: local-schema-registry
