apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-configure-vault
spec:
  template:
    spec:
      containers:
        - name: kafka-configure-vault
          image: nathanmyles/vault-client:1.0.0
          command: ["/bin/sh"]
          args:
            - -ec
            - |
              curl http://local-vault.default/ca_cert.crt > /ca_cert.crt
              export VAULT_CACERT="/ca_cert.crt"
              export VAULT_ADDR="https://local-vault.default:8200"
              vault login root_token
              cat >> policy.hcl <<EOF
                path "pki/issue/kafka-default" {
                  capabilities = ["create", "update"]
                }
              EOF
              vault policy write local-kafka policy.hcl
              vault write auth/kubernetes/role/local-kafka \
                bound_service_account_names=local-kafka \
                bound_service_account_namespaces=default \
                policies=default,local-kafka \
                ttl=1h
              vault write pki/roles/kafka-default \
                  allowed_domains=local-kafka.default \
                  allow_subdomains=true \
                  max_ttl=72h
      restartPolicy: Never
