apiVersion: v1
kind: Service
metadata:
  name: local-vault
spec:
  selector:
    app: local-vault
  clusterIP: None
  # We want the servers to become available even if they're not ready
  # since this DNS is also used for join operations.
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
