apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-vault
  labels:
    app: local-vault
spec:
  serviceName: local-vault
  replicas: 1
  selector:
    matchLabels:
      app: local-vault
  template:
    metadata:
      labels:
        app: local-vault
    spec:
      serviceAccountName: local-vault
      containers:
        - name: local-vault
          image: vault:1.3.0
          command: ["/bin/sh"]
          args:
            - -ec
            - |
              export VAULT_ADDR="http://local-vault.default:8200"
              export VAULT_API_ADDR="http://local-vault.default:8200"
              export VAULT_FORMAT="json"
              vault server -config=/etc/vault/config.hcl &
              process_id=$!
              sleep 5
              vault operator unseal $(cat /var/lib/vault/secrets/unseal_1)
              vault operator unseal $(cat /var/lib/vault/secrets/unseal_2)
              vault operator unseal $(cat /var/lib/vault/secrets/unseal_3)
              wait $process_id
          imagePullPolicy: Always
          ports:
            - containerPort: 8200
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          readinessProbe:
            # Check status; unsealed vault servers return 0
            # The exit code reflects the seal status:
            #   0 - unsealed
            #   1 - error
            #   2 - sealed
            exec:
              command:
                - "/bin/sh"
                - "-ec"
                - |
                  export VAULT_ADDR="http://127.0.0.1:8200"
                  vault status | if [ $? -ne 1 ]; then exit 0; fi
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
          - name: vault-data
            mountPath: /var/lib/vault/data
          - name: secrets
            mountPath: /var/lib/vault/secrets
          - name: config-volume
            mountPath: /etc/vault
      initContainers:
        - name: configure
          image:  nathanmyles/vault-client:1.0.0
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          command: ["/bin/sh"]
          args:
            - -ec
            - |
              export VAULT_ADDR="http://127.0.0.1:8200"
              export VAULT_FORMAT="json"
              vault server -config=/etc/vault/config.hcl &
              sleep 2
              vault operator init > /var/lib/vault/secrets/init.json
              root_token=$(cat /var/lib/vault/secrets/init.json | jq -r .root_token)
              cat /var/lib/vault/secrets/init.json | jq -r .unseal_keys_hex[0] > /var/lib/vault/secrets/unseal_1
              cat /var/lib/vault/secrets/init.json | jq -r .unseal_keys_hex[1] > /var/lib/vault/secrets/unseal_2
              cat /var/lib/vault/secrets/init.json | jq -r .unseal_keys_hex[2] > /var/lib/vault/secrets/unseal_3
              vault operator unseal $(cat /var/lib/vault/secrets/unseal_1)
              vault operator unseal $(cat /var/lib/vault/secrets/unseal_2)
              vault operator unseal $(cat /var/lib/vault/secrets/unseal_3)
              vault login $root_token
              vault token create -id=root_token
              chmod -R 0775 /var/lib/vault/data
          volumeMounts:
            - name: vault-data
              mountPath: /var/lib/vault/data
            - name: secrets
              mountPath: /var/lib/vault/secrets
            - name: config-volume
              mountPath: /etc/vault
      volumes:
        - name: secrets
          emptyDir: {}
        - name: config-volume
          configMap:
            name: vault-config
  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: fast
        resources:
          requests:
            storage: 1Gi