apiVersion: v1
kind: Service
metadata:
  labels:
    app: local-cassandra
  name: local-cassandra
spec:
  clusterIP: None
  ports:
  - name: cql
    port: 9042
  - name: tls-cql
    port: 9142
  selector:
    app: local-cassandra
