apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-cassandra
  labels:
    app: local-cassandra
spec:
  serviceName: local-cassandra
  replicas: 1
  selector:
    matchLabels:
      app: local-cassandra
  template:
    metadata:
      labels:
        app: local-cassandra
    spec:
      serviceAccountName: local-cassandra
      containers:
      - name: local-cassandra
        image: cassandra:3.11.5
        command: ["/bin/sh"]
        args:
          - -ec
          - |
            cp /cassandra_config/cassandra.yaml /etc/cassandra/cassandra.yaml
            cp /cassandra_config/cassandra-rackdc.properties /etc/cassandra/cassandra-rackdc.properties
            /docker-entrypoint.sh
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9142
          name: tls-cql
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - |
                if openssl x509 -checkend 86400 -noout -in /usr/local/lib/cassandra/conf/certificate.pem
                then
                  exit 0
                else
                  cp /usr/local/lib/cassandra/conf/next_certificate.pem /usr/local/lib/cassandra/conf/certificate.pem
                  cp /usr/local/lib/cassandra/conf/next_truststore.jks /usr/local/lib/cassandra/conf/truststore.jks
                  cp /usr/local/lib/cassandra/conf/next_keystore.jks /usr/local/lib/cassandra/conf/keystore.jks
                  exit 1
                fi
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 300
          failureThreshold: 1
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              if [[ $(nodetool status | grep $POD_IP) == *"UN"* ]]; then
                exit 0
              else
                exit 1
              fi
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
        - name: certs
          mountPath: /usr/local/lib/cassandra/conf/
        - name: config-volume
          mountPath: /cassandra_config/
      - name: renew-certs
        image: nathanmyles/vault-client-java:1.0.0
        command: ["/bin/sh"]
        args:
          - -ec
          - |
            while true;
            do
            sleep 3600
            if openssl x509 -checkend 90000 -noout -in /certs/certificate.pem
            then
             echo "####### Certs Valid, Sleeping... #######\n"
             continue
            fi
            rm -f /certs/inprogress_truststore.jks
            rm -f /certs/inprogress_keystore.jks
            curl http://local-vault.default/ca_cert.crt > /ca_cert.crt
            export VAULT_CACERT="/ca_cert.crt"
            export VAULT_ADDR="https://local-vault.default:8200"
            export VAULT_FORMAT="json"
            vault write auth/kubernetes/login \
              role=local-cassandra \
              jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) > /tmp/login.json
            vault login $(cat /tmp/login.json | jq -r .auth.client_token) > /dev/null 2>&1
            vault write pki/issue/cassandra-default \
              common_name=${HOSTNAME}.local-cassandra.default > /certs/certs.json
            cat /certs/certs.json | jq -r .data.certificate > /certs/next_certificate.pem
            cat /certs/certs.json | jq -r .data.issuing_ca > /certs/next_issuing_ca.pem
            cat /certs/certs.json | jq -r .data.private_key > /certs/next_private_key.pem
            openssl pkcs12 -export -out /certs/next_private_key.pkcs12 -in /certs/next_certificate.pem -inkey /certs/next_private_key.pem -passin pass: -passout pass:abcdef
            keytool -genkey -keyalg RSA -alias endeca -keystore /certs/inprogress_truststore.jks -storepass abcdef <<EOF
            Unknown
            Unknown
            Unknown
            Unknown
            Unknown
            Unknown
            yes
            yes
            EOF
            keytool -delete -alias endeca -keystore /certs/inprogress_truststore.jks -storepass abcdef
            keytool -import -v -trustcacerts -alias endeca-ca -file /certs/next_issuing_ca.pem -keystore /certs/inprogress_truststore.jks -storepass abcdef <<EOF
            yes
            EOF
            keytool -genkey -keyalg RSA -alias endeca -keystore /certs/inprogress_keystore.jks -storepass abcdef<<EOF
            Unknown
            Unknown
            Unknown
            Unknown
            Unknown
            Unknown
            yes
            yes
            EOF
            keytool -delete -alias endeca -keystore /certs/inprogress_keystore.jks -storepass abcdef
            keytool -v -importkeystore -srckeystore /certs/next_private_key.pkcs12 -srcstoretype PKCS12 -destkeystore /certs/inprogress_keystore.jks -deststoretype JKS -storepass abcdef --srcstorepass abcdef <<EOF
            yes
            EOF
            cp /certs/inprogress_truststore.jks /certs/next_truststore.jks
            cp /certs/inprogress_keystore.jks /certs/next_keystore.jks
            echo "\n####### Certs Renewed #######\n"
            done
        volumeMounts:
          - name: certs
            mountPath: "/certs"
      initContainers:
      - name: fetch-certs
        image: nathanmyles/vault-client-java:1.0.0
        command: ["/bin/sh"]
        args:
          - -ec
          - |
            curl http://local-vault.default/ca_cert.crt > /ca_cert.crt
            export VAULT_CACERT="/ca_cert.crt"
            export VAULT_ADDR="https://local-vault.default:8200"
            export VAULT_FORMAT="json"
            vault write auth/kubernetes/login \
              role=local-cassandra \
              jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) > /tmp/login.json
            vault login $(cat /tmp/login.json | jq -r .auth.client_token) > /dev/null 2>&1
            vault write pki/issue/cassandra-default \
              common_name=${HOSTNAME}.local-cassandra.default > /certs/certs.json
            cat /certs/certs.json | jq -r .data.certificate > /certs/certificate.pem
            cat /certs/certs.json | jq -r .data.issuing_ca > /certs/issuing_ca.pem
            cat /certs/certs.json | jq -r .data.private_key > /certs/private_key.pem
            openssl pkcs12 -export -out /certs/private_key.pkcs12 -in /certs/certificate.pem -inkey /certs/private_key.pem -passin pass: -passout pass:abcdef
            keytool -genkey -keyalg RSA -alias endeca -keystore /certs/truststore.jks -storepass abcdef <<EOF
            Unknown
            Unknown
            Unknown
            Unknown
            Unknown
            Unknown
            yes
            yes
            EOF
            keytool -delete -alias endeca -keystore /certs/truststore.jks -storepass abcdef
            keytool -import -v -trustcacerts -alias endeca-ca -file /certs/issuing_ca.pem -keystore /certs/truststore.jks -storepass abcdef <<EOF
            yes
            EOF
            keytool -genkey -keyalg RSA -alias endeca -keystore /certs/keystore.jks -storepass abcdef<<EOF
            Unknown
            Unknown
            Unknown
            Unknown
            Unknown
            Unknown
            yes
            yes
            EOF
            keytool -delete -alias endeca -keystore /certs/keystore.jks -storepass abcdef
            keytool -v -importkeystore -srckeystore /certs/private_key.pkcs12 -srcstoretype PKCS12 -destkeystore /certs/keystore.jks -deststoretype JKS -storepass abcdef --srcstorepass abcdef <<EOF
            yes
            EOF
        volumeMounts:
          - name: certs
            mountPath: "/certs"
      volumes:
        - name: certs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: cassandra-config
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
