apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-cassandra
  labels:
    app: local-cassandra
spec:
  serviceName: local-cassandra
  replicas: 1
  selector:
    matchLabels:
      app: local-cassandra
  template:
    metadata:
      labels:
        app: local-cassandra
    spec:
      serviceAccountName: local-cassandra
      containers:
      - name: local-cassandra
        image: cassandra:3.11.5
        command: ["/bin/sh"]
        args:
          - -ec
          - |
            cp /cassandra_config/cassandra.yaml /etc/cassandra/cassandra.yaml
            cp /cassandra_config/cassandra-rackdc.properties /etc/cassandra/cassandra-rackdc.properties
            /docker-entrypoint.sh
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9142
          name: tls-cql
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - 'if [[ $(nodetool status | grep $POD_IP) == *"UN"* ]]; then exit 0; else exit 1; fi'
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
        - name: config-volume
          mountPath: /cassandra_config/
      volumes:
        - name: config-volume
          configMap:
            name: cassandra-config
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
