apiVersion: v1
kind: Service
metadata:
  labels:
    app: local-kafka
  name: local-kafka
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: client
  - port: 9093
    name: tls-client
  selector:
    app: local-kafka
