apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-kafka
  labels:
    app: local-kafka
spec:
  serviceName: local-kafka
  replicas: 1
  selector:
    matchLabels:
      app: local-kafka
  template:
    metadata:
      labels:
        app: local-kafka
    spec:
      serviceAccountName: local-kafka
      containers:
      - name: local-kafka
        image: confluentinc/cp-kafka:5.3.1
        command: [ "bash", "-c"]
        args:
        - |
          cp /kafka_config/server.properties /etc/kafka/server.properties
          kafka-server-start /etc/kafka/server.properties \
            --override broker.id=$((${HOSTNAME//[!0-9]/}+1)) \
            --override advertised.listeners=PLAINTEXT://${HOSTNAME}.local-kafka.default:9092
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
          name: client
        - containerPort: 9093
          name: tls-client
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka
        - name: config-volume
          mountPath: /kafka_config/
      volumes:
        - name: config-volume
          configMap:
            name: kafka-config
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast
      resources:
        requests:
          storage: 1Gi
